FROM carcraft-22268-frontend-dependencies:local
USER root
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
RUN /app/node_modules/.bin/playwright install --with-deps chromium
WORKDIR /workspace
