"""Application-layer errors and domain error mapping."""

from domain.additional_options import InvalidAdditionalOptionsError
from domain.dealer_distribution import DealerDistributionConflictError
from domain.errors import (
    AccessDeniedError,
    AccountingDataNotFoundError,
    AccountingProviderUnavailableError,
    ApplicationCreateIdempotencyConflictError,
    ApplicationDocumentNotFoundError,
    ApplicationLcAssignmentNotAllowedError,
    ApplicationNotEditableError,
    ApplicationNotFoundError,
    ApplicationNotOwnedError,
    ApplicationNotSubmittableError,
    ApplicationVehicleAssignmentError,
    ApplicationVehicleFulfillmentRequiredError,
    ApplicationVehicleNotFoundError,
    BidAlreadyAcceptedError,
    BidAlreadyExistsError,
    BillOfLadingFileNotFoundError,
    BulkImportValidationError,
    CartCustomPriceDeniedError,
    CartItemNotFoundError,
    CityAlreadyExistsError,
    CityNotFoundError,
    ClientProfileNotFoundError,
    CodeAlreadySentError,
    CompanyAccessDeniedError,
    CompanyAlreadyDeactivatedError,
    CompanyAlreadyExistsError,
    CompanyHasNoInnError,
    CompanyLookupUnavailableError,
    CompanyNotFoundError,
    CompanySpecialEquipmentConflictError,
    CompensationDocumentsRequiredError,
    CompensationNotFoundError,
    DealerAlreadyLinkedError,
    DealerAssignmentNotAllowedError,
    DealerGroupAlreadyExistsError,
    DealerGroupNotFoundError,
    DealerInviteError,
    DealerNotFoundError,
    DealerOptionAlreadyExistsError,
    DealerOptionNotFoundError,
    DealerRoleRequiredError,
    DistributorAccessDeniedError,
    DistributorDealerLinkNotFoundError,
    DistributorNotFoundError,
    DistributorScopeMissingError,
    DocumentAccessDeniedError,
    DocumentNotFoundError,
    DocumentRecognitionFailedError,
    DocumentRequestAlreadyExistsError,
    DocumentRequestNotFoundError,
    DocumentTypeNotFoundError,
    DocumentVersionConflictError,
    DomainError,
    EmployeeAssignmentNotAllowedError,
    ExcelFormatError,
    ExchangeBidAccessDeniedError,
    ExchangeBidNotFoundError,
    ExchangeCartEmptyError,
    ExchangeCartItemNotFoundError,
    ExchangeRequestAccessDeniedError,
    ExchangeRequestNotFoundError,
    FavoriteAlreadyExistsError,
    FavoriteNotFoundError,
    FeaturedAlreadyExistsError,
    FeaturedNotFoundError,
    FileTooLargeError,
    GuestCartTransferConflictError,
    ImageNotFoundError,
    IncompleteProposalError,
    InsufficientVehiclesError,
    Invalid2FAActionError,
    InvalidBidStatusError,
    InvalidCalculationParamsError,
    InvalidCartQuantityError,
    InvalidCityError,
    InvalidCompanyPayloadError,
    InvalidCompanyTypeError,
    InvalidCompensationStatusError,
    InvalidCompensationValueError,
    InvalidDateRangeError,
    InvalidDealerGroupError,
    InvalidDealerOptionError,
    InvalidDealerProfilePayloadError,
    InvalidDocumentReviewError,
    InvalidDocumentStatusError,
    InvalidExchangeRequestStatusError,
    InvalidExportFormatError,
    InvalidFeaturedReorderError,
    InvalidImageError,
    InvalidInnError,
    InvalidLeasingCompanyApplicationStatusError,
    InvalidOrderStatusError,
    InvalidPhoneChangeError,
    InvalidReportTypeError,
    InvalidRoleError,
    InvalidSignatureError,
    InvalidStatusTransitionError,
    InvalidSupportProgramError,
    InvalidUploadError,
    InvalidVehicleError,
    InvalidVerificationCodeError,
    InvalidWarehouseError,
    LeasingCompanyAccessDeniedError,
    LeasingCompanyApplicationNotFoundError,
    LeasingCompanyBindingNotConfiguredError,
    LeasingCompanyNotFoundError,
    LeasingProposalAlreadyDecidedError,
    LeasingProposalNotFoundError,
    LeasingProposalNotSubmittedError,
    LeasingRatesNotConfiguredError,
    MarkNotFoundError,
    ModelNotFoundError,
    NoAvailableVinsError,
    NotificationNotFoundError,
    ObjectStorageUnavailableError,
    OrderNotFoundError,
    PaymentGatewayError,
    PaymentNotFoundError,
    PhoneAlreadyInUseError,
    PriceUnavailableError,
    RejectReasonRequiredError,
    ReportsAccessDeniedError,
    RequestedDocumentsRequiredError,
    RequirementsUpdateAccessDeniedError,
    ResponseAlreadySubmittedError,
    ResponsePdfMissingError,
    SavedCalculationNotFoundError,
    ScheduleItemAlreadyPaidError,
    ScheduleItemMismatchError,
    ScheduleItemNotFoundError,
    SopdSignerResolutionError,
    SopdTemplateNotFoundError,
    StatusHistoryNotFoundError,
    SupportNotFoundError,
    SupportProgramNotFoundError,
    TooManyCompensationsError,
    UnsupportedFileTypeError,
    UserAlreadyExistsError,
    UserDeactivatedError,
    UserEmailAlreadyExistsError,
    UserNotFoundError,
    VehicleAlreadyInWarehouseError,
    VehicleNotAvailableError,
    VehicleNotFoundError,
    VehicleNotInWarehouseError,
    VinAlreadyAssignedError,
    WarehouseCascadeConfirmationInvalidError,
    WarehouseCascadeDeleteBlockedError,
    WarehouseCascadePreviewStaleError,
    WarehouseNotFoundError,
    ZeroCalculationBaseError,
)
from domain.fast_deals.errors import (
    FastDealAccessDeniedError,
    FastDealConflictError,
    FastDealFileTooLargeError,
    FastDealNotFoundError,
    FastDealReserveConflictError,
    FastDealStateError,
    FastDealValidationError,
    FastDealVersionConflictError,
    FastDealVersionRequiredError,
)
from domain.monetization.errors import (
    MonetizationAccessDeniedError,
    MonetizationConflictError,
    MonetizationValidationError,
)
from domain.special_equipment_application_pricing import (
    PriceOnRequestPendingError,
)
from domain.special_equipment_attachments import (
    AttachmentCategoryInUseError,
    AttachmentInvariantError,
)
from domain.special_equipment_management import (
    AttributeTypeConversionBlockedError,
    ProductPriceOnRequestModeLockedError,
    ProductWarehouseValidationError,
    SpecialEquipmentManagementConflictError,
    SpecialEquipmentManagementIntegrityError,
    SpecialEquipmentManagementNotFoundError,
    SpecialEquipmentManagementPreconditionError,
    SpecialEquipmentManagementValidationError,
    SpecialEquipmentTrimContractError,
)
from domain.storefront_pages import (
    InvalidBuilderMediaError,
    InvalidPageLayoutError,
    InvalidPagePresetError,
    StorefrontPageAlreadyExistsError,
    StorefrontPageNotFoundError,
    StorefrontPageRevisionNotFoundError,
    StorefrontPageVersionConflictError,
    StorefrontTemplateNotFoundError,
)
from domain.storefront_transfer import (
    InvalidStorefrontTransferError,
    StaleStorefrontPreviewError,
)
from domain.storefronts import (
    CurrentHomePageHiddenError,
    DefaultStorefrontMutationError,
    InvalidPublicUIConfigError,
    InvalidStorefrontAppearanceError,
    InvalidStorefrontContactError,
    InvalidStorefrontFontError,
    InvalidStorefrontLogoError,
    InvalidStorefrontSlugError,
    ReservedStorefrontSlugError,
    StorefrontFontContentConflictError,
    StorefrontFontNameConflictError,
    StorefrontFontNotFoundError,
    StorefrontLogoNotFoundError,
    StorefrontNotFoundError,
    StorefrontSlugConflictError,
    StorefrontWarehouseRequiredError,
)


class ServiceError(Exception):
    def __init__(
        self,
        message: str,
        status_code: int = 400,
        *,
        code: str | None = None,
        requested: int | None = None,
        available: int | None = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.code = code
        self.requested = requested
        self.available = available

    def structured_payload(self) -> dict[str, str | int] | None:
        """Return a stable top-level API error when the use case carries one."""

        if self.code is None:
            return None
        payload: dict[str, str | int] = {
            "code": self.code,
            "message": str(self),
        }
        if self.requested is not None:
            payload["requested"] = self.requested
        if self.available is not None:
            payload["available"] = self.available
        return payload


_DOMAIN_HTTP_MAP: dict[type, int] = {
    # Fast deals: 404 also hides foreign resources, 412/428 are version checks.
    FastDealNotFoundError: 404,
    FastDealAccessDeniedError: 403,
    FastDealValidationError: 422,
    FastDealStateError: 409,
    FastDealConflictError: 409,
    FastDealReserveConflictError: 409,
    FastDealVersionConflictError: 412,
    FastDealVersionRequiredError: 428,
    FastDealFileTooLargeError: 413,
    MonetizationValidationError: 400,
    MonetizationConflictError: 409,
    MonetizationAccessDeniedError: 403,
    ApplicationCreateIdempotencyConflictError: 409,
    InvalidAdditionalOptionsError: 422,
    AttributeTypeConversionBlockedError: 409,
    AttachmentCategoryInUseError: 409,
    AttachmentInvariantError: 422,
    SpecialEquipmentManagementIntegrityError: 500,
    SpecialEquipmentManagementNotFoundError: 404,
    SpecialEquipmentManagementConflictError: 409,
    SpecialEquipmentManagementPreconditionError: 412,
    ProductWarehouseValidationError: 422,
    ProductPriceOnRequestModeLockedError: 409,
    SpecialEquipmentManagementValidationError: 422,
    SpecialEquipmentTrimContractError: 409,
    OrderNotFoundError: 404,
    VehicleNotFoundError: 404,
    PaymentNotFoundError: 404,
    ScheduleItemNotFoundError: 404,
    UserNotFoundError: 404,
    CompensationNotFoundError: 404,
    SupportNotFoundError: 404,
    NotificationNotFoundError: 404,
    ImageNotFoundError: 404,
    PriceUnavailableError: 400,
    InvalidOrderStatusError: 400,
    ScheduleItemAlreadyPaidError: 400,
    InvalidVerificationCodeError: 400,
    InvalidCompensationStatusError: 400,
    InvalidCompensationValueError: 400,
    CompensationDocumentsRequiredError: 400,
    ZeroCalculationBaseError: 400,
    TooManyCompensationsError: 400,
    InvalidImageError: 400,
    AccessDeniedError: 403,
    ScheduleItemMismatchError: 403,
    CodeAlreadySentError: 403,
    InvalidSignatureError: 403,
    VehicleNotAvailableError: 409,
    InsufficientVehiclesError: 409,
    UserAlreadyExistsError: 409,
    PaymentGatewayError: 502,
    UserDeactivatedError: 401,
    CompanyLookupUnavailableError: 503,
    SopdSignerResolutionError: 422,
    ObjectStorageUnavailableError: 503,
    AccountingProviderUnavailableError: 503,
    AccountingDataNotFoundError: 404,
    CompanyNotFoundError: 404,
    CompanyAccessDeniedError: 403,
    InvalidCalculationParamsError: 400,
    LeasingRatesNotConfiguredError: 503,
    SupportProgramNotFoundError: 404,
    InvalidSupportProgramError: 400,
    DealerGroupNotFoundError: 404,
    InvalidDealerGroupError: 400,
    DealerGroupAlreadyExistsError: 409,
    LeasingCompanyNotFoundError: 404,
    DistributorNotFoundError: 404,
    InvalidUploadError: 400,
    BillOfLadingFileNotFoundError: 404,
    DealerNotFoundError: 404,
    CityNotFoundError: 404,
    CityAlreadyExistsError: 409,
    InvalidCityError: 400,
    WarehouseNotFoundError: 404,
    WarehouseCascadeConfirmationInvalidError: 422,
    WarehouseCascadeDeleteBlockedError: 409,
    WarehouseCascadePreviewStaleError: 409,
    InvalidWarehouseError: 400,
    VehicleAlreadyInWarehouseError: 409,
    VehicleNotInWarehouseError: 404,
    MarkNotFoundError: 404,
    DealerOptionNotFoundError: 404,
    DealerOptionAlreadyExistsError: 409,
    InvalidDealerOptionError: 400,
    ClientProfileNotFoundError: 404,
    FavoriteAlreadyExistsError: 409,
    FavoriteNotFoundError: 404,
    SavedCalculationNotFoundError: 404,
    InvalidPhoneChangeError: 400,
    PhoneAlreadyInUseError: 409,
    InvalidVehicleError: 400,
    VinAlreadyAssignedError: 409,
    NoAvailableVinsError: 404,
    ModelNotFoundError: 404,
    FeaturedAlreadyExistsError: 409,
    FeaturedNotFoundError: 404,
    InvalidFeaturedReorderError: 400,
    ApplicationVehicleNotFoundError: 404,
    ApplicationVehicleAssignmentError: 400,
    ApplicationVehicleFulfillmentRequiredError: 409,
    DealerAlreadyLinkedError: 409,
    DistributorAccessDeniedError: 403,
    DistributorDealerLinkNotFoundError: 404,
    ExcelFormatError: 400,
    BulkImportValidationError: 413,
    ApplicationNotFoundError: 404,
    ApplicationNotOwnedError: 403,
    InvalidStatusTransitionError: 400,
    ApplicationNotSubmittableError: 400,
    DealerAssignmentNotAllowedError: 400,
    DealerDistributionConflictError: 409,
    EmployeeAssignmentNotAllowedError: 400,
    DocumentNotFoundError: 404,
    DocumentAccessDeniedError: 403,
    InvalidDocumentStatusError: 400,
    DocumentVersionConflictError: 409,
    UnsupportedFileTypeError: 400,
    FileTooLargeError: 413,
    DocumentRecognitionFailedError: 422,
    DocumentTypeNotFoundError: 404,
    SopdTemplateNotFoundError: 404,
    ApplicationDocumentNotFoundError: 404,
    DocumentRequestNotFoundError: 404,
    DocumentRequestAlreadyExistsError: 409,
    RequirementsUpdateAccessDeniedError: 403,
    InvalidDocumentReviewError: 400,
    LeasingCompanyAccessDeniedError: 403,
    LeasingCompanyApplicationNotFoundError: 404,
    InvalidLeasingCompanyApplicationStatusError: 400,
    LeasingCompanyBindingNotConfiguredError: 400,
    RejectReasonRequiredError: 400,
    RequestedDocumentsRequiredError: 400,
    StatusHistoryNotFoundError: 404,
    LeasingProposalNotFoundError: 404,
    LeasingProposalNotSubmittedError: 400,
    LeasingProposalAlreadyDecidedError: 409,
    IncompleteProposalError: 400,
    ResponseAlreadySubmittedError: 409,
    ResponsePdfMissingError: 404,
    CartItemNotFoundError: 404,
    InvalidCartQuantityError: 400,
    CartCustomPriceDeniedError: 403,
    GuestCartTransferConflictError: 409,
    ExchangeRequestNotFoundError: 404,
    ExchangeRequestAccessDeniedError: 403,
    InvalidExchangeRequestStatusError: 400,
    ExchangeBidNotFoundError: 404,
    ExchangeBidAccessDeniedError: 403,
    InvalidBidStatusError: 400,
    BidAlreadyAcceptedError: 409,
    BidAlreadyExistsError: 409,
    ExchangeCartItemNotFoundError: 404,
    ExchangeCartEmptyError: 400,
    DealerInviteError: 400,
    ApplicationNotEditableError: 400,
    ReportsAccessDeniedError: 403,
    InvalidReportTypeError: 400,
    InvalidExportFormatError: 400,
    InvalidDateRangeError: 400,
    DistributorScopeMissingError: 400,
    # Admin residual domain (Phase 6 — F2)
    InvalidRoleError: 400,
    UserEmailAlreadyExistsError: 409,
    CompanyAlreadyExistsError: 409,
    InvalidCompanyTypeError: 400,
    InvalidInnError: 400,
    ApplicationLcAssignmentNotAllowedError: 400,
    PriceOnRequestPendingError: 409,
    StorefrontNotFoundError: 404,
    StorefrontLogoNotFoundError: 404,
    StorefrontSlugConflictError: 409,
    DefaultStorefrontMutationError: 409,
    InvalidStorefrontTransferError: 422,
    StaleStorefrontPreviewError: 409,
    InvalidStorefrontSlugError: 422,
    ReservedStorefrontSlugError: 422,
    StorefrontWarehouseRequiredError: 422,
    InvalidStorefrontLogoError: 422,
    InvalidStorefrontContactError: 422,
    InvalidPublicUIConfigError: 422,
    InvalidStorefrontAppearanceError: 422,
    InvalidStorefrontFontError: 422,
    StorefrontFontNotFoundError: 404,
    StorefrontFontNameConflictError: 409,
    StorefrontFontContentConflictError: 409,
    CurrentHomePageHiddenError: 409,
    # Storefront constructor pages
    StorefrontPageNotFoundError: 404,
    StorefrontPageAlreadyExistsError: 409,
    StorefrontPageVersionConflictError: 409,
    StorefrontPageRevisionNotFoundError: 404,
    StorefrontTemplateNotFoundError: 404,
    InvalidPageLayoutError: 422,
    InvalidPagePresetError: 422,
    InvalidBuilderMediaError: 422,
    # G4 — dealer/client/companies gaps
    CompanyHasNoInnError: 400,
    InvalidCompanyPayloadError: 400,
    CompanyAlreadyDeactivatedError: 409,
    CompanySpecialEquipmentConflictError: 409,
    DealerRoleRequiredError: 403,
    InvalidDealerProfilePayloadError: 400,
    Invalid2FAActionError: 400,
}


def domain_to_http(exc: DomainError) -> ServiceError:
    """Convert a domain error into a ServiceError with the right HTTP status."""
    code = _DOMAIN_HTTP_MAP.get(type(exc), 400)
    error_code = getattr(exc, "code", None)
    return ServiceError(
        str(exc),
        code,
        code=error_code,
    )
