export const questionnaireLabels: Record<string, string> = {
  "full_company_name": "Полное наименование компании",
  "foreign_company_name": "Наименование на иностранном языке",
  "vehicle_id": "Позиция заявки",
  "short_company_name": "Сокращённое наименование",
  "inn": "ИНН компании",
  "kpp": "КПП",
  "ogrn": "ОГРН",
  "okpo": "ОКПО",
  "okato": "ОКАТО",
  "legal_form": "Организационно-правовая форма",
  "tax_system": "Система налогообложения",
  "okved_main": "Основной ОКВЭД",
  "okved_additional": "Дополнительные ОКВЭД",
  "registration_date": "Дата регистрации",
  "registration_authority_name": "Регистрирующий орган",
  "legal_address": "Юридический адрес",
  "actual_address": "Фактический адрес",
  "actual_address_same_as_legal": "Фактический адрес совпадает с юридическим",
  "actual_address_details": "Детализация фактического адреса",
  "postal_address": "Почтовый адрес",
  "legal_address_matches_registration": "Совпадение юридического адреса с адресом регистрации",
  "postal_address_matches_legal": "Совпадение юридического адреса с почтовым адресом",
  "phone": "Телефон контактного лица",
  "email": "Email контактного лица",
  "website": "Сайт, существующее поле",
  "company_phone": "Телефон организации",
  "company_email": "Email организации",
  "company_website": "Сайт организации",
  "contact_person": "ФИО, должность, телефон и email контактного лица",
  "fax": "Факс",
  "bank_name": "Наименование банка",
  "bik": "БИК",
  "settlement_account": "Расчётный счёт",
  "correspondent_account": "Корреспондентский счёт",
  "director_full_name": "ФИО руководителя",
  "director_surname": "Фамилия руководителя",
  "director_first_name": "Имя руководителя",
  "director_patronymic": "Отчество руководителя",
  "director_position": "Должность руководителя",
  "director_inn": "ИНН руководителя",
  "director_snils": "СНИЛС руководителя",
  "director_sex": "Пол руководителя",
  "director_citizenship": "Гражданство руководителя",
  "director_birth_date": "Дата рождения руководителя",
  "director_birth_place": "Место рождения руководителя",
  "director_passport_series": "Серия паспорта",
  "director_passport_number": "Номер паспорта",
  "director_passport_issued_by": "Кем выдан паспорт",
  "director_passport_issue_date": "Дата выдачи паспорта",
  "director_passport_department_code": "Код подразделения",
  "director_registration_address": "Адрес регистрации руководителя",
  "director_birth_country": "Страна рождения руководителя",
  "director_registration_country": "Страна регистрации руководителя",
  "director_registration_postal_code": "Почтовый индекс регистрации руководителя",
  "director_registration_house": "Дом по адресу регистрации руководителя",
  "director_registration_apartment": "Квартира по адресу регистрации руководителя",
  "director_registration_date": "Дата регистрации руководителя по месту жительства",
  "director_actual_address": "Фактический адрес руководителя",
  "director_actual_country": "Страна фактического проживания руководителя",
  "director_actual_postal_code": "Почтовый индекс фактического проживания руководителя",
  "director_actual_house": "Дом по фактическому адресу руководителя",
  "director_actual_apartment": "Квартира по фактическому адресу руководителя",
  "director_actual_same_as_registration": "Фактический адрес руководителя совпадает с адресом регистрации",
  "director_phone": "Телефон руководителя",
  "director_email": "Email руководителя",
  "director_appointment_document": "Документ о назначении руководителя",
  "director_is_pdl": "Руководитель является ПДЛ или родственником ПДЛ",
  "director_pdl_related_person": "ФИО ПДЛ или родственника ПДЛ",
  "director_name_changed": "Отметка о смене ФИО",
  "founders": "Учредители",
  "beneficiaries": "Бенефициарные владельцы",
  "has_beneficiary": "Наличие бенефициарного владельца",
  "beneficiary_info": "Дополнительные сведения о бенефициаре",
  "other_representatives": "Другие представители",
  "management_bodies": "Органы управления",
  "employee_count": "Среднесписочная численность сотрудников",
  "licenses_or_sro_membership": "Лицензии и членство в СРО",
  "main_counterparties": "Основные контрагенты",
  "open_bank_accounts": "Открытые расчётные счета",
  "loans_credits_leasing": "Кредиты, займы и лизинг",
  "third_party_guarantees": "Поручительства за третьих лиц",
  "additional_collateral_available": "Возможность дополнительного обеспечения",
  "vehicle_purchase_purpose": "Цели приобретения ТС",
  "management_company_details": "Сведения об управляющей компании",
  "requisites": "Реквизиты управляющей компании",
  "transaction_beneficiary": "Выгодоприобретатель по сделке",
  "electronic_document_management_systems": "Используемые системы ЭДО",
  "website_in_blocked_domains_registry": "Сайт в реестре запрещённых доменов",
  "state_defense_order": "Наличие гособоронзаказа",
  "personal_data_processing_consent": "Согласие на обработку персональных данных",
  "legal_entity_credit_report_consent": "Согласие на кредитный отчёт юрлица",
  "individual_credit_report_consent": "Согласие на кредитный отчёт физлица",
  "credit_bureau_data_transfer_consent": "Согласие на передачу данных в БКИ",
  "marketing_communications_consent": "Согласие на рекламные рассылки",
  "information_accuracy_declaration": "Заверение о достоверности сведений",
  "information_verification_consent": "Согласие на проверку информации",
  "permitted_data_recipients": "Банки и партнёры для передачи данных",
  "telecom_data_transfer_consent": "Согласие на передачу данных операторам связи",
  "federal_register_inclusion_consent": "Согласие на включение в федеральный реестр",
  "affiliates_data_transfer_consent": "Согласие на передачу аффилированным лицам",
  "electronic_documents_equivalence_consent": "Электронные документы равнозначны бумажным",
  "automated_marketing_consent": "Согласие на автоматические рассылки",
  "biometric_data_processing_consent": "Согласие на обработку биометрии",
  "consent_validity_period": "Срок действия согласий",
  "consent_revocation_procedure": "Порядок отзыва согласий",
  "questionnaire_completed_at": "Дата и время заполнения анкеты",
  "authorized_person_signature": "Подпись руководителя или представителя",
  "company_seal": "Оттиск печати",
  "created_at": "Дата создания анкеты",
  "updated_at": "Дата изменения анкеты",
  "full_name": "ФИО",
  "name": "Наименование",
  "position": "Должность",
  "surname": "Фамилия",
  "first_name": "Имя",
  "patronymic": "Отчество",
  "birth_date": "Дата рождения",
  "birth_place": "Место рождения",
  "citizenship": "Гражданство",
  "sex": "Пол",
  "passport_series": "Серия паспорта",
  "passport_number": "Номер паспорта",
  "passport_issued_by": "Кем выдан",
  "passport_issue_date": "Дата выдачи",
  "passport_department_code": "Код подразделения",
  "registration_address": "Адрес регистрации",
  "share_percentage": "Доля владения, %",
  "beneficial_owner_basis": "Основание отнесения к бенефициарам",
  "beneficial_owner_basis_details": "Уточнение основания",
  "no_beneficial_owner_reason": "Причина отсутствия бенефициара",
  "no_beneficial_owner_reason_details": "Уточнение причины",
  "is_pdl": "Является ПДЛ или родственником ПДЛ",
  "pdl_related_person_name": "ФИО ПДЛ или родственника",
  "name_changed": "Отметка о смене ФИО",
  "bank": "Банк",
  "acc_number": "Расчётный счёт",
  "fio": "ФИО",
  "counterparties": "Контрагенты",
  "comment": "Комментарий",
  "accounts": "Счета",
  "vehicles": "Транспортные средства",
  "purposes": "Цели приобретения",
  "sopd_number": "Номер СОПД",
  "sopd_date": "Дата подписания",
  "valid_until": "Действует до",
  "sbis": "СБИС",
  "diadoc": "Диадок",
  "kontur": "Контур",
  "other": "Другая система",
  "other_name": "Название системы",
  "not_used": "Системы ЭДО не используются",
  "signer_name": "Подписант",
  "document_type": "Тип документа",
  "user_title": "Название документа"
}
