"""sync_models

Revision ID: 004
Revises: 003
Create Date: 2026-05-20 12:14:26.439225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounting_metadata', 'period_years',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'organization',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'audit_report',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'year_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'computed_ratios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'period_years',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'organization',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'balance_sheet',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'financial_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'cash_flow',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'capital_change',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'audit_report',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'year_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'computed_ratios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'founders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'beneficiaries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'other_representatives',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'management_bodies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(None, 'application_questionnaires', ['application_id'])
    op.alter_column('balance_sheet', 'xml_raw',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_calculation_history_created_at'), table_name='calculation_history')
    op.create_index('idx_calculation_history_created_at', 'calculation_history', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('capital_changes', 'xml_raw',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cash_flow', 'xml_raw',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('client_profiles', 'notification_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'contact_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'legal_address_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'additional_okved_list',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'founders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_distributor_id'), table_name='companies')
    op.drop_constraint(op.f('companies_distributor_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'distributor_id')
    op.alter_column('compensations', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key('FK_configuration_generation', 'configuration', 'generation', ['generation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('distributors', 'regions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('distributors', 'brands',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_types', 'validation_rules',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'extracted_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('financial_result', 'xml_raw',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key('FK_generation_model', 'generation', 'model', ['model_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('leasing_applications', 'requested_documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_leasing_applications_distributor_id'), table_name='leasing_applications')
    op.drop_constraint(op.f('leasing_applications_distributor_id_fkey'), 'leasing_applications', type_='foreignkey')
    op.drop_column('leasing_applications', 'distributor_id')
    op.alter_column('leasing_calculations', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('leasing_calculations', 'calculation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('leasing_companies', 'special_offers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(None, 'magic_links', ['token'])
    op.create_foreign_key('FK_model_mark', 'model', 'mark', ['mark_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('FK_modification_configuration', 'modification', 'configuration', ['configuration_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key('FK_options_modification', 'options', 'modification', ['complectation_id'], ['complectation_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('passport_recognition_data', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('passport_recognition_data', 'mapped_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('passport_recognition_data', 'confidence_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('payments', 'gateway_response',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payments', 'fiscal_response',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('signature_requests', 'subject_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('signature_requests', 'signing_ip',
               existing_type=sa.VARCHAR(length=45),
               type_=postgresql.INET(),
               existing_nullable=True,
               postgresql_using='signing_ip::inet')
    op.create_foreign_key('FK_specifications_modification', 'specifications', 'modification', ['complectation_id'], ['complectation_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('support_programs', 'support_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('support_programs', 'show_to_leasing_company',
               existing_type=sa.BOOLEAN(),
               comment='Показывать программу лизинговой компании в админке',
               existing_nullable=True)
    op.alter_column('support_programs', 'show_to_client',
               existing_type=sa.BOOLEAN(),
               comment='Показывать программу клиенту (калькулятор, корзина)',
               existing_nullable=True)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=postgresql.INET(),
               existing_nullable=True,
               postgresql_using='ip_address::inet')
    op.drop_index(op.f('idx_user_sessions_user_id_last_used_at_desc'), table_name='user_sessions')
    op.create_index('idx_user_sessions_user_id_last_used_at_desc', 'user_sessions', ['user_id', sa.literal_column('last_used_at DESC')], unique=False)
    op.alter_column('users', 'mfa_backup_codes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('vehicles', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'mfa_backup_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_user_sessions_user_id_last_used_at_desc', table_name='user_sessions')
    op.create_index(op.f('idx_user_sessions_user_id_last_used_at_desc'), 'user_sessions', ['user_id', 'last_used_at'], unique=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('support_programs', 'show_to_client',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Показывать программу клиенту (калькулятор, корзина)',
               existing_nullable=True)
    op.alter_column('support_programs', 'show_to_leasing_company',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Показывать программу лизинговой компании в админке',
               existing_nullable=True)
    op.alter_column('support_programs', 'support_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('FK_specifications_modification', 'specifications', type_='foreignkey')
    op.alter_column('signature_requests', 'signing_ip',
               existing_type=postgresql.INET(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('signature_requests', 'subject_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('payments', 'fiscal_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payments', 'gateway_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('passport_recognition_data', 'confidence_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('passport_recognition_data', 'mapped_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('passport_recognition_data', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint('FK_options_modification', 'options', type_='foreignkey')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('FK_modification_configuration', 'modification', type_='foreignkey')
    op.drop_constraint('FK_model_mark', 'model', type_='foreignkey')
    op.drop_constraint(None, 'magic_links', type_='unique')
    op.alter_column('leasing_companies', 'special_offers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('leasing_calculations', 'calculation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('leasing_calculations', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('leasing_applications', sa.Column('distributor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leasing_applications_distributor_id_fkey'), 'leasing_applications', 'companies', ['distributor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_leasing_applications_distributor_id'), 'leasing_applications', ['distributor_id'], unique=False)
    op.alter_column('leasing_applications', 'requested_documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('FK_generation_model', 'generation', type_='foreignkey')
    op.alter_column('financial_result', 'xml_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_types', 'validation_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('distributors', 'brands',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('distributors', 'regions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('FK_configuration_generation', 'configuration', type_='foreignkey')
    op.alter_column('compensations', 'documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('companies', sa.Column('distributor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('companies_distributor_id_fkey'), 'companies', 'companies', ['distributor_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_companies_distributor_id'), 'companies', ['distributor_id'], unique=False)
    op.alter_column('companies', 'founders',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'additional_okved_list',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'legal_address_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'contact_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('companies', 'address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('client_profiles', 'notification_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cash_flow', 'xml_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('capital_changes', 'xml_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_calculation_history_created_at', table_name='calculation_history')
    op.create_index(op.f('idx_calculation_history_created_at'), 'calculation_history', ['created_at'], unique=False)
    op.alter_column('balance_sheet', 'xml_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'application_questionnaires', type_='unique')
    op.alter_column('application_questionnaires', 'management_bodies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'other_representatives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'beneficiaries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application_questionnaires', 'founders',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'computed_ratios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'year_files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'audit_report',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'capital_change',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'cash_flow',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'financial_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'balance_sheet',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'organization',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_reports', 'period_years',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'computed_ratios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'year_files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'audit_report',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'organization',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accounting_metadata', 'period_years',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
