FROM imbios/bun-node:latest-20.19.1-debian
USER root
WORKDIR /app
COPY frontend/package.json frontend/bun.lock ./
RUN bun install --frozen-lockfile
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV LANG=C.UTF-8
RUN /app/node_modules/.bin/playwright install --with-deps chromium
WORKDIR /workspace
